### ISSUE TITLE
why do you use Splunk

### ISSUE THREAD

**Issue by fizz12344321** [signalfx/splunk-otel-java-overhead-test#71]
Hi, i am reading your repository and i love it, but i have a question, why do you use Splunk ? Can u tell me your purpose, the pros and cons of Splunk, why don't u use Micrometer, Prometheus, grafana. Thank u so much

**Comment by mateuszrzeszutek** [comment]
Hey @fizz12344321 ,
As I wrote in https://github.com/signalfx/splunk-otel-android/issues/307#issuecomment-1167018754, we are Splunk.
